---
- hosts: ansible-moodle
  become: yes
  tasks:
    - name: F端hre Apt Update aus.
      ansible.builtin.apt:
        update_cache: yes
    - name: Installiere MariaDB.
      ansible.builtin.apt:
        pkg:
        - mariadb-server
        - mariadb-client 
    - name: Installiere Apache2.
      ansible.builtin.apt:
        pkg:
        - apache2
        - apache2-doc
    - name: Erstelle und akiviere SSL-Zertifikat.
      ansible.builtin.shell: |
          a2enmod ssl && 
          systemctl restart apache2
          openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/apache-selfsigned.key -out /etc/ssl/certs/apache-selfsigned.crt -nodes -subj "/C=DE/ST=NRW/L=Bochum/O=Moodle Install/OU=Private/CN=192.168.81.145"
    - name: Erstelle conf-Datei f端r Moodle.
      ansible.builtin.file:
        path: /etc/apache2/sites-available/moodle.conf
        state: touch
    - name: Konfiguiere conf-Datei f端r Moodle.
      ansible.builtin.blockinfile:
        path: /etc/apache2/sites-available/moodle.conf
        block: |
            <VirtualHost *:443>
              ServerName 192.168.81.145
              DocumentRoot /var/www/html/moodle

              SSLEngine on
              SSLCertificateFile /etc/ssl/certs/apache-selfsigned.crt
              SSLCertificateKeyFile /etc/ssl/private/apache-selfsigned.key
            </VirtualHost>
    - name: Erstelle Web-Verzeichnis Moodle.
      ansible.builtin.file:
        path: /var/www/html/moodle
        state: directory
        owner: www-data
        group: www-data
    - name: Aktiviere SSL-Verbindung f端r Moodle.
      ansible.builtin.shell: a2ensite moodle
    - name: Installiere PHP und PHP-MySQL
      ansible.builtin.apt:
        pkg:
        - php
        - php-mysql
    - name: Erstelle PHP-Info Datei.
      ansible.builtin.lineinfile:
        path: /var/www/html/moodle/test.php
        line: <?php phpinfo(); ?>
        create: yes
    - name: Starte Apache2 neu.
      ansible.builtin.service:
        name: apache2
        state: reloaded

    #- name: Aktiviere 000-default.conf via a2enmod
    #  ansible.builtin.shell: a2enmod 000-default.conf

        

  
